version: '3'
services:
  my-app-front:
    image: mariomafdy/frontend
    ports:
     - 3000:3000
    environment:
     - MONGODB_URI=mongodb://admin:password@mongodb:27017
    depends_on:
     - "mongodb"
  my-app-back:
    image: mariomafdy/backend
    ports:
     - 7000:7000
    environment:
     - MONGODB_URI=mongodb://admin:password@mongodb:27017
    depends_on:
     - "mongodb"
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - "mongodb"
volumes:
  mongo-data:
    driver: local