{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
spec:
  selector:
    matchLabels:
      app: {{ include "frontend.fullname" . }}
  endpoints:
  - port: http
    interval: 15s
{{- end }}