global:
  host: 57d6e0a8122c.mylabserver.com

frontend:
  replicaCount: 1
  image:
    repository: mariomafdy/frontend
    tag: latest
  service:
    type: NodePort
    port: 3000
    nodePort: 30082
  env:
    backendUrl: "http://{{ .Values.global.host }}:30083"

backend:
  replicaCount: 1
  image:
    repository: mariomafdy/backend
    tag: latest
  service:
    type: NodePort
    port: 7000
    nodePort: 30083
  env:
    port: "7000"
    mongoUri: "mongodb://admin:password@mongodb:27017/todo?authSource=admin"

mongodb:
  persistence:
    enabled: true
    storageClass: "manual"
    size: 1Gi
  auth:
    username: admin
    password: password

mongoExpress:  # Changed from "mongo-express"
  enabled: true
  image:
    repository: mongo-express
    tag: latest
  service:
    type: NodePort
    port: 8081
    nodePort: 30081
  env:
    adminUser: admin
    adminPassword: password

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

nginx:
  service:
    type: NodePort
    httpPort: 80
    httpsPort: 443
    httpNodePort: 30080
    httpsNodePort: 30443