global:
  host: 57d6e0a8122c.mylabserver.com

frontend:
  replicaCount: 1
  image:
    repository: mariomafdy/frontend
    tag: latest
  service:
    type: NodePort
    port: 3000
    nodePort: 30082
  env:
    backendUrl: "http://{{ .Values.global.host }}:30083"

backend:
  replicaCount: 1
  image:
    repository: mariomafdy/backend
    tag: latest
  service:
    type: NodePort
    port: 7000
    nodePort: 30083
  env:
    port: "7000"
    mongoUri: "mongodb://admin:password@mongodb:27017/todo?authSource=admin"

mongodb:
  persistence:
    enabled: true
    storageClass: "manual"
    size: 1Gi
  auth:
    username: admin
    password: password

mongoExpress:  # Changed from "mongo-express"
  enabled: true
  image:
    repository: mongo-express
    tag: latest
  service:
    type: NodePort
    port: 8081
    nodePort: 30081
  env:
    adminUser: admin
    adminPassword: password

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

nginx:
  service:
    type: NodePort
    httpPort: 80
    httpsPort: 443
    httpNodePort: 30080
    httpsNodePort: 30443

# Monitoring
prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi
    service:
      type: NodePort
      nodePort: 30900

grafana:
  enabled: true
  adminUser: admin
  adminPassword: "grafana-secret"
  service:
    type: NodePort
    nodePort: 30901
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server:80
        access: proxy
        isDefault: true
  dashboards:
    default:
      todo-dashboard:
        gnetId: 1860
        revision: 2
        datasource: Prometheus

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: "manual"
    size: 2Gi
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

prometheus-node-exporter:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node.kubernetes.io/unschedulable"
      operator: "Exists"
      effect: "NoSchedule"