apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  hostPath:
    path: /mnt/data