{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.global.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "frontend.fullname" . }}
            port:
              number: {{ .Values.frontend.service.port }}
      - path: /mongo-express
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: {{ .Values.mongoExpress.service.port }}
{{- end }}