# apiVersion: v1
# kind: Service
# metadata:
#   name: ingress-nginx-controller
# spec:
#   selector:
#     app: ingress-nginx
#   ports:
#     - name: http
#       protocol: TCP
#       port: {{ .Values.nginx.service.httpPort }}
#       targetPort: 80
#       nodePort: {{ .Values.nginx.service.httpNodePort }}
#     - name: https
#       protocol: TCP
#       port: {{ .Values.nginx.service.httpsPort }}
#       targetPort: 443
#       nodePort: {{ .Values.nginx.service.httpsNodePort }}
#   type: {{ .Values.nginx.service.type }}