name: Publish Helm Chart

on:
  push:
    branches:
      - deployment   # adjust if needed
    paths:
      - 'app/**'     # only run if the chart changes

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Package Helm chart
        run: |
          mkdir -p charts
          helm package ./app --destination charts

      - name: Create or update index.yaml
        run: |
          helm repo index charts --url https://mariomafdyhabib.github.io/grad_project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
          publish_branch: gh-pages
 